name: GitHub Classroom Workflow

on: 
  push:
    paths:
    - 'src/assignment.lean'

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      - run: echo "$HOME/.elan/bin" >> $GITHUB_PATH
      - name: classroom autograding
        uses: education/autograding@v1